name: Deploy to aws

on:
  push:
    branches:
    - master
jobs:
  deploy-to-aws:
    name: deploy-to-aws
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v1

    - name: install venv
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.12'
    - name: Get req & pem & tfvar & sql file
      uses: chrislennon/action-aws-cli@v1.1
    - run: |
        aws s3 cp s3://comiccrawler-data/v4/req.json .
        aws s3 cp s3://comiccrawler-data/v4/comic-db.pem .
        aws s3 cp s3://comiccrawler-data/v4/terraform.tfvars env/v4_only_db
        aws s3 cp s3://comiccrawler-data/v4/prod_db_build.sql env
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Run terraform
      run: |
        cd env/v4_only_db
        terraform init
        terraform plan -out dev.tfplan
        terraform apply dev.tfplan || touch build_failed.txt
        if [ -f "build_failed.txt" ]
        then
          terraform plan -destroy -out destroy.tfplan && terraform apply destroy.tfplan
          exit 1
        fi
