name: Test the CodeGenerator

on:
  push:
    branches:
    - crawl_engine
jobs:
  test-code-generator:
    name: test-code-generator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.10'
        node-version: '8.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: TestCodeGenerator
      env:
        LANG: "C.UTF-8"
      run: |
        python tests/code_generator_tests.py
