name: Test the StorageEngine

on:
  push:
    branches:
    - storage_engine
jobs:
  test-storage-engine:
    name: test-storage-engine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.10'
        node-version: '8.x'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: TestStorageEngine(JsonStorageDriver)
      run: |-
        python tests/storage_engine_tests.py
